name: Publish Helm Chart to GHCR

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Helm Chart metadata
        id: chart
        uses: jacobtomlinson/gha-read-helm-chart@master
        with:
          path: helm/oci-native-ingress-controller

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        run: |
          helm package helm/oci-native-ingress-controller --version "${{ steps.chart.outputs.version }}" --app-version "${{ steps.chart.outputs.appVersion }}"
          ls -lh

      - name: Push to GHCR
        run: |
          helm push "${{ steps.chart.outputs.name }}-${{ steps.chart.outputs.version }}.tgz" oci://ghcr.io/${{ github.repository_owner }}/charts
